# isort: skip_file
from __future__ import annotations

from typing import overload

from .unit import Unit
from .quantity import Quantity, QuantitySetter, UnitApplier, UnitChanger

class AccelerationSetter(QuantitySetter[Acceleration]):
    @property
    def foot_per_square_second(self) -> Acceleration: ...
    @property
    def meter_per_square_second(self) -> Acceleration: ...

class Acceleration(Quantity[Acceleration]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[Acceleration] | None = None) -> None: ...
    class ToUnit(UnitApplier[Acceleration]):
        @property
        def foot_per_square_second(self) -> Acceleration: ...
        @property
        def meter_per_square_second(self) -> Acceleration: ...

        def __call__(self, unit: Unit[Acceleration] | str) -> Acceleration: ...

    class AsUnit(UnitChanger[Acceleration]):
        @property
        def foot_per_square_second(self) -> Acceleration: ...
        @property
        def meter_per_square_second(self) -> Acceleration: ...

        def __call__(self, unit: Unit[Acceleration] | str) -> Acceleration: ...

    @property
    def to_unit(self) -> Acceleration.ToUnit: ...

    @property
    def as_unit(self) -> Acceleration.AsUnit: ...

    @overload
    def set(self, value: float) -> AccelerationSetter: ...
    @overload
    def set(self, value: float, unit: Unit[Acceleration]) -> Acceleration: ...
    @overload
    def set(self, value: float, unit: str) -> Acceleration: ...

class LengthSetter(QuantitySetter[Length]):
    @property
    def foot(self) -> Length: ...
    @property
    def inch(self) -> Length: ...
    @property
    def meter(self) -> Length: ...
    @property
    def millimeter(self) -> Length: ...

class Length(Quantity[Length]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[Length] | None = None) -> None: ...
    class ToUnit(UnitApplier[Length]):
        @property
        def foot(self) -> Length: ...
        @property
        def inch(self) -> Length: ...
        @property
        def meter(self) -> Length: ...
        @property
        def millimeter(self) -> Length: ...

        def __call__(self, unit: Unit[Length] | str) -> Length: ...

    class AsUnit(UnitChanger[Length]):
        @property
        def foot(self) -> Length: ...
        @property
        def inch(self) -> Length: ...
        @property
        def meter(self) -> Length: ...
        @property
        def millimeter(self) -> Length: ...

        def __call__(self, unit: Unit[Length] | str) -> Length: ...

    @property
    def to_unit(self) -> Length.ToUnit: ...

    @property
    def as_unit(self) -> Length.AsUnit: ...

    @overload
    def set(self, value: float) -> LengthSetter: ...
    @overload
    def set(self, value: float, unit: Unit[Length]) -> Length: ...
    @overload
    def set(self, value: float, unit: str) -> Length: ...

class DimensionlessSetter(QuantitySetter[Dimensionless]):
    @property
    def dimensionless(self) -> Dimensionless: ...

class Dimensionless(Quantity[Dimensionless]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[Dimensionless] | None = None) -> None: ...
    class ToUnit(UnitApplier[Dimensionless]):
        @property
        def dimensionless(self) -> Dimensionless: ...

        def __call__(self, unit: Unit[Dimensionless] | str) -> Dimensionless: ...

    class AsUnit(UnitChanger[Dimensionless]):
        @property
        def dimensionless(self) -> Dimensionless: ...

        def __call__(self, unit: Unit[Dimensionless] | str) -> Dimensionless: ...

    @property
    def to_unit(self) -> Dimensionless.ToUnit: ...

    @property
    def as_unit(self) -> Dimensionless.AsUnit: ...

    @overload
    def set(self, value: float) -> DimensionlessSetter: ...
    @overload
    def set(self, value: float, unit: Unit[Dimensionless]) -> Dimensionless: ...
    @overload
    def set(self, value: float, unit: str) -> Dimensionless: ...

class PressureSetter(QuantitySetter[Pressure]):
    @property
    def Pa(self) -> Pressure: ...
    @property
    def pascal(self) -> Pressure: ...
    @property
    def pascals(self) -> Pressure: ...
    @property
    def pound_force_per_square_inch(self) -> Pressure: ...

class Pressure(Quantity[Pressure]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[Pressure] | None = None) -> None: ...
    class ToUnit(UnitApplier[Pressure]):
        @property
        def Pa(self) -> Pressure: ...
        @property
        def pascal(self) -> Pressure: ...
        @property
        def pascals(self) -> Pressure: ...
        @property
        def pound_force_per_square_inch(self) -> Pressure: ...

        def __call__(self, unit: Unit[Pressure] | str) -> Pressure: ...

    class AsUnit(UnitChanger[Pressure]):
        @property
        def Pa(self) -> Pressure: ...
        @property
        def pascal(self) -> Pressure: ...
        @property
        def pascals(self) -> Pressure: ...
        @property
        def pound_force_per_square_inch(self) -> Pressure: ...

        def __call__(self, unit: Unit[Pressure] | str) -> Pressure: ...

    @property
    def to_unit(self) -> Pressure.ToUnit: ...

    @property
    def as_unit(self) -> Pressure.AsUnit: ...

    @overload
    def set(self, value: float) -> PressureSetter: ...
    @overload
    def set(self, value: float, unit: Unit[Pressure]) -> Pressure: ...
    @overload
    def set(self, value: float, unit: str) -> Pressure: ...

class MassDensitySetter(QuantitySetter[MassDensity]):
    @property
    def kilogram_per_cubic_meter(self) -> MassDensity: ...
    @property
    def ounce_per_milliliter(self) -> MassDensity: ...
    @property
    def pound_mass_per_cubic_foot(self) -> MassDensity: ...

class MassDensity(Quantity[MassDensity]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[MassDensity] | None = None) -> None: ...
    class ToUnit(UnitApplier[MassDensity]):
        @property
        def kilogram_per_cubic_meter(self) -> MassDensity: ...
        @property
        def ounce_per_milliliter(self) -> MassDensity: ...
        @property
        def pound_mass_per_cubic_foot(self) -> MassDensity: ...

        def __call__(self, unit: Unit[MassDensity] | str) -> MassDensity: ...

    class AsUnit(UnitChanger[MassDensity]):
        @property
        def kilogram_per_cubic_meter(self) -> MassDensity: ...
        @property
        def ounce_per_milliliter(self) -> MassDensity: ...
        @property
        def pound_mass_per_cubic_foot(self) -> MassDensity: ...

        def __call__(self, unit: Unit[MassDensity] | str) -> MassDensity: ...

    @property
    def to_unit(self) -> MassDensity.ToUnit: ...

    @property
    def as_unit(self) -> MassDensity.AsUnit: ...

    @overload
    def set(self, value: float) -> MassDensitySetter: ...
    @overload
    def set(self, value: float, unit: Unit[MassDensity]) -> MassDensity: ...
    @overload
    def set(self, value: float, unit: str) -> MassDensity: ...

class ViscosityDynamicSetter(QuantitySetter[ViscosityDynamic]):
    @property
    def pascal_second(self) -> ViscosityDynamic: ...
    @property
    def poise(self) -> ViscosityDynamic: ...
    @property
    def pound_force_second_per_square_foot(self) -> ViscosityDynamic: ...

class ViscosityDynamic(Quantity[ViscosityDynamic]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[ViscosityDynamic] | None = None) -> None: ...
    class ToUnit(UnitApplier[ViscosityDynamic]):
        @property
        def pascal_second(self) -> ViscosityDynamic: ...
        @property
        def poise(self) -> ViscosityDynamic: ...
        @property
        def pound_force_second_per_square_foot(self) -> ViscosityDynamic: ...

        def __call__(self, unit: Unit[ViscosityDynamic] | str) -> ViscosityDynamic: ...

    class AsUnit(UnitChanger[ViscosityDynamic]):
        @property
        def pascal_second(self) -> ViscosityDynamic: ...
        @property
        def poise(self) -> ViscosityDynamic: ...
        @property
        def pound_force_second_per_square_foot(self) -> ViscosityDynamic: ...

        def __call__(self, unit: Unit[ViscosityDynamic] | str) -> ViscosityDynamic: ...

    @property
    def to_unit(self) -> ViscosityDynamic.ToUnit: ...

    @property
    def as_unit(self) -> ViscosityDynamic.AsUnit: ...

    @overload
    def set(self, value: float) -> ViscosityDynamicSetter: ...
    @overload
    def set(self, value: float, unit: Unit[ViscosityDynamic]) -> ViscosityDynamic: ...
    @overload
    def set(self, value: float, unit: str) -> ViscosityDynamic: ...

class ViscosityKinematicSetter(QuantitySetter[ViscosityKinematic]):
    @property
    def foot_squared_per_second(self) -> ViscosityKinematic: ...
    @property
    def square_meter_per_second(self) -> ViscosityKinematic: ...

class ViscosityKinematic(Quantity[ViscosityKinematic]):
    def __init__(self, name: str, value: float | None = None, preferred: Unit[ViscosityKinematic] | None = None) -> None: ...
    class ToUnit(UnitApplier[ViscosityKinematic]):
        @property
        def foot_squared_per_second(self) -> ViscosityKinematic: ...
        @property
        def square_meter_per_second(self) -> ViscosityKinematic: ...

        def __call__(self, unit: Unit[ViscosityKinematic] | str) -> ViscosityKinematic: ...

    class AsUnit(UnitChanger[ViscosityKinematic]):
        @property
        def foot_squared_per_second(self) -> ViscosityKinematic: ...
        @property
        def square_meter_per_second(self) -> ViscosityKinematic: ...

        def __call__(self, unit: Unit[ViscosityKinematic] | str) -> ViscosityKinematic: ...

    @property
    def to_unit(self) -> ViscosityKinematic.ToUnit: ...

    @property
    def as_unit(self) -> ViscosityKinematic.AsUnit: ...

    @overload
    def set(self, value: float) -> ViscosityKinematicSetter: ...
    @overload
    def set(self, value: float, unit: Unit[ViscosityKinematic]) -> ViscosityKinematic: ...
    @overload
    def set(self, value: float, unit: str) -> ViscosityKinematic: ...
